[build]
# The directory containing your static assets
publish = "public"
# ðŸ’¡ Netlify will now look for compiled functions in this new directory.
functions = "functions-build" 
command = "npm run build" 

[[redirects]]
# This maps all requests starting with /api/ to the Netlify function handler
from = "/api/*"
# The Netlify function name must match the filename in your output directory (api.js)
to = "/.netlify/functions/api/:splat"
status = 200

[[redirects]]
# This redirects all other root requests to the static index.html file
from = "/"
to = "/index.html"
status = 200